profile:
  message: "DEFAULT profile"

spring:
  datasource:
    url: jdbc:postgresql://localhost/mgr-database
    username: mgr-user
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # datasource:
  #   url: jdbc:postgresql://ep-icy-hat-974631.eu-central-1.aws.neon.tech/neondb
  #   username: kam.flis99
  #   password: GgHiQldD8KZ4
  #   driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    # hibernate:
    #   ddl-auto: update

